services:

  phpunuhi:
    container_name: phpunuhi
    image: dockware/flex:latest
    volumes:
      - "../../:/app"
    ports:
      - "22:22"
    working_dir: /app
    environment:
      - PHP_VERSION=8.2
      - XDEBUG_ENABLED=1