name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'makefile'


env:
  PHP_VERSION: 8.2

jobs:

  # ------------------------------------------------------------------------------------------------------------------------

  review:
    name: Review Pipeline
    uses: ./.github/workflows/step_review.yml
    with:
      PHP_VERSION: ${{ env.PHP_VERSION }}

  # ------------------------------------------------------------------------------------------------------------------------

  release:
    name: Release Pipeline
    uses: ./.github/workflows/step_release.yml
    secrets:
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      PACKAGIST_USER: "${{ secrets.PACKAGIST_USER }}"
      PACKAGIST_TOKEN: "${{ secrets.PACKAGIST_TOKEN }}"
    with:
      VERSION: "dev-master"
      PHP_VERSION: ${{ env.PHP_VERSION }}
