name: Release Version
run-name: Release ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:

  # ------------------------------------------------------------------------------------------------------------------------

  review:
    name: Review Pipeline
    uses: ./.github/workflows/step_review.yml
    with:
      PHP_VERSION: 8.2

  # ------------------------------------------------------------------------------------------------------------------------

  checks:
    name: Release Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
        # -----------------------------------
      - name: Check XSD for release version
        run: |
          php tests/scripts/check_xsd.php ${{ github.event.inputs.version }}

  # ------------------------------------------------------------------------------------------------------------------------

  release:
    name: Release Pipeline
    uses: ./.github/workflows/step_release.yml
    needs: [ review, checks ]
    secrets:
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      PACKAGIST_USER: "${{ secrets.PACKAGIST_USER }}"
      PACKAGIST_TOKEN: "${{ secrets.PACKAGIST_TOKEN }}"
    with:
      VERSION: ${{ github.event.inputs.version }}
      PHP_VERSION: 8.2
