name: Step Review

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true
    inputs:
      VERSION:
        description: "PHPUnuhi Version"
        required: true
        type: string
      PHP_VERSION:
        description: "PHP Version"
        required: true
        type: string


jobs:

  checks:
    name: Release Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Check Release
        run: |
          make check-release version=${{ inputs.VERSION }}

  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          ini-values: phar.readonly=OFF
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-build-${{ github.run_id }}
          path: |
            .build
            vendor
        # -----------------------------------
      - name: Build Artifacts
        run: |
          make prod
          make build -B
          make artifact

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-build-${{ github.run_id }}
          path: |
            .build
            vendor
        # -----------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # -----------------------------------
      - name: Build Docker Image
        run: make docker version=${{ inputs.VERSION }}
        # -----------------------------------
      - name: Push Docker Image
        run: |
          docker push boxblinkracer/phpunuhi:${{ inputs.VERSION }}

  # ------------------------------------------------------------------------------------------------------------------------

  packagist:
    name: Update Packagist
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      # -----------------------------------
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Invoke Packagist Webhook
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USER }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/boxblinkracer/phpunuhi"}}'
